### ISSUE TITLE
Unclear: "turn the solutions off"

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/koans#10]
This phrase in the README.md is unclear.
Why does the user need to "turn the solutions off"? 
Why is this not done by default?

Also,

> (... ./solutions off from the root of the project).
> Go to the root directory: cd koans

This is not handy...first go to the root; then from there do `./solutions off`; then ...

**Comment by anatoliykmetyuk** [comment]
> Why does the user need to "turn the solutions off"? 

He doesn't. So far there's no stable release, so they need to clone from github. This is not normal and will change in future. When we have a release, they'll need to download a zip file prepared for them. You can take a look at what it looks like by running `./release 1.0` and going to `distribution` folder.

> This is not handy...first go to the root; then from there do ./solutions off; then ...

The setup I'm using for the development is a terminal with 2 tabs - one with `sbt`, another at the root of the project. This way, switching the solutions is as easy as committing to github.

**Comment by anatoliykmetyuk** [comment]
Everything in italic will be removed once the work on the first stable version is finished. The `Download` link will then point to the first stable release's zip file, hosted on github releases.

**Comment by anatoliykmetyuk** [comment]
I modified the readme earlier.
