### ISSUE TITLE
problem with `runWithInput` or `thenActivatedOrSuccess`

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/koans#11]
From AboutIterations:

```
script..
  s = b c d / ..?

test(1) {runWithInput(s)(           ); thenActivatedOrSuccess(__`b`)}
test(2) {runWithInput(s)(b          ); thenActivatedOrSuccess(__`b,c`)}
show(3) {runWithInput(s)(b,b        ); thenActivatedOrSuccess(__`b,c`)}
test(4) {runWithInput(s)(b,b,c      ); thenActivatedOrSuccess(__`b,d`)}
```

>   Test 3: Set(b) did not contain only (b, c) (OperatorKoansHelper.scala:46)

I think this is a problem with `runWithInput` or `thenActivatedOrSuccess`.
Namely, test 4 is allowed to proceed with `c`, and then `d` is activated.

**Comment by anatoliykmetyuk** [comment]
I fixed it - do you have any unpushed changes? Can I push?

**Comment by AndreVanDelft** [comment]
No and yes :-)

**Comment by anatoliykmetyuk** [comment]
Note that I've changed SubScript version to `3.0.2-SNAPSHOT`, so you need to pull the SubScript repository and push it to the local maven repository.
