### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/koans#14]
I would like to see the UI improved.
Instead of having to do type

> set javaOptions in Test += "-Dmax=10"
> set javaOptions in Test += "-Dshow=1"

Setting the maximum would be nice to serve as a default value. By default this should be 10 or 100.
The `show` setting is unnecessary IMO, if we replace `test-only` by `test` and `show`.

`PTE` should be an alias for `PathToEnlightenment`.
Also it should be possible to specify Abouts; if only one is specified then also koan; and optionally also test.

There should also be options to run tests in the graphical debugger, using the task `debug`, and in the textual debugger, using the task `trace`. For these tasks there is no `max:` parameter.

How these tasks will run depends on whether a specific test is do be performed or not.
If so, then that test is run in the appropriate debugger.
Else all applicable tests are run, until one fails. Then that test is replayed using the appropriate debugger, without the appended call to `S`.

E.g.

> test PathToEnlightenment max:3
> test PTE max:3
> test AboutIterations AboutDataflow max:3
> test AboutIterations koan:6 
> test AboutIterations koan:6 test:3
> 
> show PTE max:50
> test AboutIterations koan:6 test:3
> 
> debug PTE
> debug AboutIterations AboutDataflow
> debug AboutIterations koan:6
> debug AboutIterations koan:6 test:3
> 
> trace PTE
> trace AboutIterations AboutDataflow
> trace AboutIterations koan:6
> trace AboutIterations koan:6 test:3

**Comment by AndreVanDelft** [comment]
Also the reporting should improve.

> [info] - Koan 6 **\* FAILED ***
> [info]   Test 5: Set(b) did not contain only (b, c)
> [info]   Test 6: Set(b) did not contain only (b, S) (KoanSuite.scala:86)
> [info] AboutAdvancedSyntax:
> [info] AboutConditionalOperators:
> [info] AboutResultValues:
> [info] AboutAdvancedResultValues:
> [info] AboutDataflow:
> [info] Run completed in 4 seconds, 274 milliseconds.
> [info] Total number of tests run: 47
> [info] Suites: completed 15, aborted 0
> [info] Tests: succeeded 46, failed 1, canceled 0, ignored 0, pending 0
> [info] **\* 1 TEST FAILED ***
> [error] Failed tests:
> [error]   PathToEnlightenment

The reported number of tests is 1 whereas it should be 2.

> Test 5: Set(b) did not contain only (b, c)

That is unclear. Better would be:

> Test 5: guessed: (b, c) actual: (b)

In case there is no answer provided, just `__` then we currently get:

> Test 7: Set(S) did not contain only ("Fill me in") (KoanSuite.scala:86)

or if the variable `show` was 0:

> Test 7 goes wrong: try again please. (KoanSuite.scala:86)

Better would be: 

> Test 7 No answer provided. (KoanSuite.scala:86)

The total number of such tests should be reported separately at the end:

> Tests failed: 3 open: 4 succeeded: 32 total: 39

**Comment by anatoliykmetyuk** [comment]
There's not much I can do about the reporting - the messages are set by scalatest. We don't have direct access to the provided/correct values.

The number of failed tests indicate the number of failed koans. The test is an artificial unit, it does not exist for scalatest. It tracks its smallest unit of koan.

I'll see what I can do about the new sbt tasks. In principle, should be possible to define them.

Currently, the debugger operates on a script as a whole. We can't tell it to track only the part visible to the user, it will track rhe entire script with S and the backend engine. Would be good to have the debugger improved in future though.

**Comment by AndreVanDelft** [comment]
Ok,the reporting is far less important than the UI.

**Comment by anatoliykmetyuk** [comment]
See updated readme for the added features.
