### ISSUE TITLE
Koan errors and glitches

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/koans#3]
I encounter several errors.
E.g., article usage, or absense thereof.

> Space operator has the smallest precedence.

Not true.

> Non-strict and-parallelism operator `&&`
> Non-strict or-parallel operator `||`
> Strict or-parallel operator `|`

This terminology is new, and I don't like it. 
In earlier publications, the operators were named as follows
&  - normal parallelism
| - weak or-parallelism
&& - strong and-parallelism
|| - strong or-parallelism
Shall we revert to that?

> """Non-strict and-parallelism operator `&&` behaves like `&`, but if one of its children doesn't succeed, it will terminate without success immediately, terminating all its remaining operands."""

That is not true. It should read:

> """Non-strict and-parallelism operator `&&` behaves like `&`, but if one of its children terminates without success, && will also terminate without success, and for that purpose it first terminates all its remaining operands."""

**Comment by AndreVanDelft** [comment]
```
"""You can use inline definition of scripts from Scala code."""
```

That deserves an extra explanation line 

```
val s = ([let a = 3])
```

should be:

```
val s = [let a = 3]
```

**Comment by AndreVanDelft** [comment]
"""Optional break `break?` works like `break`, but once an activation
    | happens in one of its previously activated operands
    | it resumes its activation sequence."""

The explanation is too limited; it should explain that `break?` means 'optional break'; it applies not only sequential contexts, but also to the other ones, in particular the parallel ones. 

I'd say: first introduce `break?` the sequential context.
And even before that, give some tests about `[b + [+]] c`.
After this is done, explain that in a sequential context, something similar happens.
And then continue with the `&&` context.

**Comment by AndreVanDelft** [comment]
script s = b while(i < 2) c {!i += 1!}

    test(2) {
      runWithInput(s)(b, c, b, c)
      activatedShouldBe()
    }

I don't get this. After the second c, i==2. Then b is activated and executed again. However the koan says that the loop would there end. 

And this is confusing:

    """As `while` is an operand, it also doesn't matter where you put it
    | in sequence."""

I would say:

    """As `while` is an operand, it may be used at any position below a parent 
    | operator such as `&&`. 
    | The position specifies the loop exit point, in case the condition is false"""

Or something like that.

**Comment by AndreVanDelft** [comment]
> ```
> """Scripts can have return types. So far, SubScript is untyped,
> | so they all must be Any. More on script results in later koans."""
> ```

should be like

> ```
> """Scripts may have result values, which are much like method return values.
> | For now the formal types of these result values is always `Any`.
> | At some point in the near future more specific types will be allowed.
> | More on script result values in later koans."""
> ```

**Comment by anatoliykmetyuk** [comment]
I don't really know how to change the descriptions of the koans in a better way, I think you'd handle this task better. So I won't touch the descriptions, ok?

**Comment by AndreVanDelft** [comment]
Yes, I already started on that. I also reorganize the PathToEnlightenment a bit: `+` will come right after `;`.
