### ISSUE TITLE
break? koan broken

### ISSUE THREAD

**Issue by AndreVanDelft** [scala-subscript/koans#5]
```
"""Optional break `break?` works like `break`, but once an activation
| happens in one of its previously activated operands
| it resumes its activation sequence."""
```

The explanation is too limited; it should explain that `break?` means 'optional break'; it applies not only sequential contexts, but also to the other ones, in particular the parallel ones. 

I'd say: first introduce `break?` the sequential context.
And even before that, give some tests about `[b + [+]] c`.
After this is done, explain that in a sequential context, something similar happens.
And then continue with the `&&` context.

Note that this 

```
"""Optional break `break?` works like `break`, but once an activation
| happens in one of its previously activated operands
| it resumes its activation sequence."""
```

holds for an alternative choice context, with the `+` operator.
For the parallel operators and '/' it would be different.
('context' needs to be explained)

```
"""In context of &, &&, |, ||, /  `break?` works like `break`, but once an atomic action
| happens in one of its previously activated operands
| it resumes its activation sequence."""
```

**Comment by anatoliykmetyuk** [comment]
I afraid I don't understand the philosophy behind `break?` well enough to describe it in a nice way; I described the semantics only in my koans. Will you handle this koan?

**Comment by AndreVanDelft** [comment]
Yes, I intend to do that.
`break?` means to say that you may or may not stop there. What this exactly means does depends on the context. In a sequence it is relatively easy to define:
`x break? y; z` = `x; [+]+y; z`
except for the fact that `y` sees the sequence as its context rather than the new `+`.

**Comment by AndreVanDelft** [comment]
The AboutIteration koans should explain well enough.
